// vue/vue05/src/components/Home.vue
<template>
  <transition name="lbt">
    <div id="home" v-if="isShow">
      <p>首页</p>
      <div class="swiper-container">
        <div class="swiper-wrapper">
          <div class="swiper-slide" v-for="(v,i) in imgArr" :key="i">
            <img :src="v" alt="">
          </div>
        </div>
        <!-- 如果需要分页器 -->
        <div class="swiper-pagination"></div>

        <!-- 如果需要导航按钮 -->
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>

        <!-- 如果需要滚动条 -->
        <div class="swiper-scrollbar"></div>
      </div>
    </div>
  </transition>
</template>

<script>
  import Swiper from 'swiper';
  import "../../node_modules/swiper/css/swiper.css";

  export default {
    name: "Home",
    mounted() {
      new Swiper('.swiper-container', {
        // direction: 'vertical', // 垂直切换选项
        loop: true, // 循环模式选项

        // 如果需要分页器
        pagination: {
          el: '.swiper-pagination',
        },

        // 如果需要前进后退按钮
        navigation: {
          nextEl: '.swiper-button-next',
          prevEl: '.swiper-button-prev',
        },

      })
    },
    data() {
      return {
        imgArr: [
          "https://place-hold.it/600x301",
          "https://place-hold.it/600x302",
          "https://place-hold.it/600x303",
          "https://place-hold.it/600x304",
          "https://place-hold.it/600x305",
          "https://place-hold.it/600x306"
        ],
        isShow: true
      }
    },
    beforeRouteEnter(to, from, next) {
      next(vm => {
        vm.isShow = true;
      });
    },
    beforeRouteLeave(to, from, next) {
      this.isShow = false;
      next();
    }
  }
</script>

<style scoped>
  #home {
    width: 100%;
    height: 65%;
    background-color: lightpink;
  }

  .swiper-container {
    width: 600px;
    height: 300px;
  }

  .lbt-enter-active, .lbt-leave-active {
    transition: opacity 2s;
  }

  .lbt-enter, .lbt-leave-to
  {
    opacity: 0;
  }
</style>

// React/react03/src/Home.js
import React, {Component} from 'react';
import "./Home.css"
import Swiper from 'swiper';
import '../node_modules/swiper/css/swiper.css'

class Home extends Component {
    constructor(props) {
        super(props);
        this.state = {
            bannerArr: []
        }
    }

    componentWillMount() {
        fetch("https://elm.cangdu.org/v2/index_entry", {method: "get"}).then((res) => {
            return res.json();
        }).then((data) => {
            console.log(data)
            for (let i = 0; i < data.length / 8; i++) {
                let subArr = data.slice(i * 8, (i + 1) * 8);
                this.setState(previousState => {
                    return {
                        bannerArr: [...previousState.bannerArr, subArr]
                    }
                }, () => {
                    var mySwiper = new Swiper('.swiper-container', {
                        // direction: 'vertical', // 垂直切换选项
                        loop: true, // 循环模式选项

                        // // 如果需要分页器
                        // pagination: {
                        //     el: '.swiper-pagination',
                        // },

                        // 如果需要前进后退按钮
                        navigation: {
                            nextEl: '.swiper-button-next',
                            prevEl: '.swiper-button-prev',
                        },

                        // 如果需要滚动条
                        // scrollbar: {
                        //     el: '.swiper-scrollbar',
                        // },
                    })
                });
                console.log(this.state.bannerArr);
            }
        }).catch((err) => {
            console.log(err)
        })
    }

    componentDidMount() {

    }

    render() {
        return <div className="home">
            <p>这是home组件</p>
            <div className="swiper-container">
                <div className="swiper-wrapper">
                    {
                        this.state.bannerArr.map((v, i) => {
                            return <div className="swiper-slide" key={i}>
                                {
                                    v.map((v1, i1) => {
                                        return <img src={'https://fuss10.elemecdn.com' + v1.image_url}
                                                    style={{width: '150px', height: '150px', float: 'left'}} key={i1}/>
                                    })
                                }
                            </div>
                        })
                    }
                </div>
                <div className="swiper-pagination"></div>
            </div>


        </div>
    }
}

export default Home;
